language: python
python:
  - "2.7"
  - "3.7"
  - "3.8"
  - "3.9" # check deployment if you remove this
#  - "3.10"
env:
  jobs:
    - TZ=Europe/Berlin
    - TZ=Australia/Sydney
install:
  # install the package
  - PACKAGE_VERSION=`python setup.py --version`
  - TAG_NAME=v$PACKAGE_VERSION
  # install from the zip file to see if files were forgotten
  - python setup.py sdist --dist-dir=dist --formats=zip
  - pip install wheel
  - ( cd dist ; pip install recurring_ical_events-${PACKAGE_VERSION}.zip )
  # install zoneinfo for the tests in older Python versions
  - if [ $TRAVIS_PYTHON_VERSION == 3.7 ] || [ $TRAVIS_PYTHON_VERSION == 3.8 ]; then pip install -r backports-requirements.txt; fi
before_script:
  # remove the build folder because it creates problems for py.test
  - rm -rf build
  # show the versions
  - python setup.py --version
  - pip list
  - echo "Package version $PACKAGE_VERSION with possible tag name $TAG_NAME"
  - python3 -c 'import time; time.tzset(); print(time.strftime("%X %x %Z"))'
script:
  # test the example script to test proper installation with all packages
  - python example.py
  # install test environment after testing example
  - pip install -r test-requirements.txt
  - pytest
  # test that the tag represents the version
  # https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables
  - ( if [ -n "$TRAVIS_TAG" ]; then if [ $TAG_NAME != $TRAVIS_TAG ]; then echo "This tag is for the wrong version. Got \"$TRAVIS_TAG\" expected \"$TAG_NAME\"."; exit 1; fi; fi; )
  # check print in release and more
  - test/test_code_quality.sh
before_deploy:
  # create the documentation
  - python setup.py sdist bdist_wheel
  # remove zip file, cannot be uploaded with .tar.gz
  # see https://app.travis-ci.com/github/niccokunzmann/x-wr-timezone/jobs/555629298#L565
  - rm -f dist/*.zip
deploy:
  # created with travis command line tool
  # https://docs.travis-ci.com/user/deployment/pypi
  # $ travis setup pypi
  provider: pypi
  user: niccokunzmann2
  password:
    secure: pEM3dshSbjGx7A+t3JisuzIhkGva0mPlZZYbZ1boNBU3Y2YiNYhhtkt8ilkGWxblmmZAq9r0UGLDY2fPlX73o6kwxIcQiwiLFFvZK+KcO7cOck35tnwWVepmMdi7x0qyjO13m1FbY1FnR9jNG7so+Pcmn1aey2XR/3Aroyx5PTDFx3SKsN8xwTtYs18Z8Huc99M7vUH9loOOsHXI0UZ5dUOk1XswDj+Zxm0stJeBqLAhMk2euh5ADBK8jNB+ZiNap8hxvKeYigB8jCP7c4YOev4nOYKAIsY15gOjBC7MSoH6668J7uiH1kgNDQyrtGHz46jKJRFke45tksefW4+gAOs8FdPVfTZR3GpnzfKxnu1yZdRktD1FOWcGZwzPpuXW9w2oGpcVt5Lh0rP7HhnK0ILnTPx7jD9c86gQiy5EhGKpgkbOsQTDIidzoVcrxDJdfS2oRyXPiHsobUNpzMTbGbnuwUKvisdHjPzhXt2/Rd/kB0Yd8KD+cdwyM6kX8ab4aevTCXWyp3hbFs+acxp0r3BZgF9T6fEWsv61ihxWV/eeWiQXmKJy1pOXEDaa/scmWDHRrxaJtXF5ASXcAIDw1pQWsqs66tcYcQC2GMsIRNpEH/TgaQ+Ozr/REWgJXNxA4NCOw7XPiDGN8pg4qjeC0zgauC8tjAaO6zQ8x85L/xU=
  on:
    tags: true
    repo: niccokunzmann/python-recurring-ical-events
    condition: $TRAVIS_PYTHON_VERSION-$TZ == 3.9-Europe/Berlin
